spring.application.name=journalApp
spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation = true
#spring.data.mongodb.username= journaluser
#spring.data.mongodb.password= mypassword