spring.application.name=journalApp
spring.data.mongodb.uri = mongodb+srv://sabrewolf05_db_user:VS5t8xF2jML99yrI@cluster0.nftz3n2.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation = true
#spring.data.mongodb.username= journaluser
#spring.data.mongodb.password= mypassword